name: deploy to Dash Enterprise 5

on:
  workflow_call:
    inputs:
      suffix:
        required: false
        type: string
      app_name:
        required: true
        type: string
      create_app:
        required: true
        type: string
    secrets:
      DASH_ENTERPRISE_PASSWORD:
        required: true
      DASH_ENTERPRISE_HOST:
        required: true
      DASH_ENTERPRISE_USERNAME:
        required: true
      ACCESS_TOKEN:
        required: true
      


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dekn-cli-python
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          python -m pip install --upgrade pip
          pip install git+https://github.com/plotly/dekn-cli-python.git
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Create helper script
        run: |
          printf '#!/bin/bash\necho username=$DASH_ENTERPRISE_USERNAME\necho password=$DASH_ENTERPRISE_PASSWORD' >> helper-script.sh
      - name: Set up git config
        run: |
          git config --global credential.helper "/bin/bash $(pwd)/helper-script.sh"
          git config --global user.email '<>' # Leave email blank
          git config --global user.name "Github Automatic Deployer"
          git config --global protocol.version 0
      - name: Inject code and deploy
        run: |
          PATH="$HOME/bin:$PATH" CREATE_APP=${{ inputs.suffix }} SUFFIX=${{ inputs.suffix }} ./deploy ${{ inputs.app_name }}
        env:
          DASH_ENTERPRISE_HOST: ${{secrets.DASH_ENTERPRISE_HOST}}
          DASH_ENTERPRISE_PASSWORD: ${{secrets.DASH_ENTERPRISE_PASSWORD}}
          DASH_ENTERPRISE_USERNAME: ${{secrets.DASH_ENTERPRISE_USERNAME}}
